backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
#publish_mode: editorial_workflow
media_folder: static/media
public_folder: /media

collections:
  - name: "post"
    label: "Posts"
    label_singular: "Post"
    description: "Post Collection"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template",
          name: "template",
          widget: hidden,
          default: single-post,
        }
      - { label: "Title", name: "title", widget: "string" }
        # defaults to current datetime
      - { label: "Publish Date", name: "publish_date", widget: "datetime" }
      - {
          label: "Author(s)",
          name: "authors",
          widget: "relation",
          collection: "authors",
          multiple: true,
          searchFields: ["name"],
          valueField: "name",
          min: 1,
        }
      - {
          label: "Category",
          name: "category",
          widget: "relation",
          collection: "categories",
          searchFields: ["title"],
          valueField: "title",
        }
      - {
          label: "Featured Image",
          name: "featured_img",
          widget: image,
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown", required: false }
      - {
          label: "Tag(s)",
          name: "tags",
          required: false,
          widget: "relation",
          collection: "tags",
          multiple: true,
          searchFields: ["title"],
          valueField: "title",
        }
      - {
          label: "Short description",
          name: short_description,
          widget: text,
          required: false,
        }

  ### CATEGORIES COLLECTION
  - name: categories
    label: "Categories"
    label_singular: "Category"
    preview: false
    folder: content/categories
    slug: "{{slug}}"
    create: true
    fields:
      - {
          label: Template,
          name: template,
          widget: hidden,
          default: post_category,
        }
      - { label: Title, name: title, widget: string }
      - { label: Subtitle, name: subtitle, widget: string, required: false }
      - {
          label: "Short description",
          name: short_description,
          widget: text,
          required: false,
        }
      - { label: Color, name: color, widget: color, required: false }

  ### TAGS COLLECTION
  - name: tags
    label: "Tags"
    label_singular: "Tag"
    preview: false
    folder: content/tags
    slug: "{{slug}}"
    create: true
    fields:
      - { label: Template, name: template, widget: hidden, default: post_tag }
      - { label: Title, name: title, widget: string }
      - { label: Subtitle, name: subtitle, widget: string, required: false }

  ### FILE TYPES COLLECTION
  - name: file_types
    label: "File types"
    label_singular: "File type"
    preview: false
    folder: content/file_types
    slug: "{{slug}}"
    create: true
    fields:
      - { label: Template, name: template, widget: hidden, default: file_type }
      - { label: Title, name: title, widget: string }
      - { label: Icon, name: icon, widget: image, required: false }
      - { label: Subtitle, name: subtitle, widget: string, required: false }

  - name: authors
    label: "Authors"
    label_singular: "Author"
    preview: false
    folder: content/author
    slug: "{{slug}}"
    create: true
    fields:
      - {
          label: Template,
          name: template,
          widget: hidden,
          default: post_author,
        }
      - { label: Name, name: name, widget: string }
      - { label: URL, name: url, widget: string, required: false }
      - {
          label: "Author image",
          name: author_img,
          widget: image,
          required: false,
        }
      - { label: Bio, name: body, widget: markdown, required: false }
